### ISSUE TITLE
Not resolving

### ISSUE THREAD

**Issue by Forecaster** [Kapilks/Download-youtube-video#1]
Hitting the "Fetch Links" button only shows the loading animation. Then it just sits there. There are no messages so I can't tell what went wrong.

It seems you might have an uncaught error or something.

**Comment by kapilks** [comment]
I think may be Youtube has change some of their API , that why its not working.
Will try fix it soon.

**Comment by Forecaster** [comment]
You might want to have it time out after a set time of not getting anything so the user can tell something is wrong.
